name: CD

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup pnpm config
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm config list

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install
          pnpm -v

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            apps/web/.next/cache
            node_modules/.cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
          
      - name: Build packages
        run: |
          echo "Building all packages..."
          pnpm build
          echo "Build completed"
          ls -la apps/web/.next || true
        
      - name: Upload repository
        uses: actions/upload-artifact@v4
        with:
          name: repo
          path: |
            .
            !.git
            !**/node_modules
            !**/.next/cache
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repo
          path: .
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup pnpm config
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm config list

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install
          pnpm list next

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            apps/web/.next/cache
            node_modules/.cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
      
      - name: Deploy to Vercel
        run: |
          echo "Deploying to Vercel..."
          npx vercel pull --yes --environment=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} 