name: CD

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            apps/web/.next/cache
            node_modules/.cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
          
      - name: Build packages
        run: |
          echo "Building all packages..."
          pnpm build
          echo "Build completed"
          ls -la apps/web/.next || true
        
      - name: Upload repository
        uses: actions/upload-artifact@v4
        with:
          name: repo
          path: |
            .
            !node_modules
            !.git
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repo
          path: .
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            apps/web/.next/cache
            node_modules/.cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_USER_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: '--prod'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          VERCEL_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} 